{{- if .Values.ingress.enabled }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "yolo.fullname" . }}
  annotations:
  {{- if .Values.ingress.tls }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect-code: '308'
  {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  defaultBackend:
    service:
      name: {{ .Release.Name }}-yolo
      port:
        number: 8001
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-yolo
            port:
              number: 8001

  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ .Release.Name }}-{{ printf "%s-tls" .Values.ingress.hostname | trunc 63 | trimSuffix "-" }}
  {{- end }}
{{- end }}
