apiVersion: v1
kind: Service
metadata:
  name: {{ include "yolo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yolo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      {{- if .Values.service.http.nodeport }}
      nodePort: {{ .Values.service.http.nodeport }}
      {{- end }}
      targetPort: {{ .Values.service.http.port }}
      protocol: {{ .Values.service.http.protocol }}
      name: {{ .Values.service.http.name }}

    {{- if .Values.https.enabled }}
    - port: {{ .Values.service.https.port }}
      {{- if .Values.service.https.nodeport }}
      nodePort: {{ .Values.service.https.nodeport }}
      {{- end }}
      targetPort: {{ .Values.service.https.port }}
      protocol: {{ .Values.service.https.protocol }}
      name: {{ .Values.service.https.name }}
    {{- end }}

  {{- if .Values.service.session.enabled }}
  {{- toYaml .Values.service.session.cfg | nindent 2 }}
  {{- end }}

  selector:
    {{- include "yolo.selectorLabels" . | nindent 4 }}
